title: Gonzalo Campos # your name (or website title) here
logo: "/images/Profile_Photo_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an aerospace engineering student at the UPC. I am eager to develop my skills as well as learn about this field, which I consider to be fascinating and thrilling. 
  <br><br>
  My portfolio features projects I've worked on or currently working on in aerospace engineering, as well as other fields.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
