title: Gonzalo Campos # your name (or website title) here
description: > # your text below
  <div style="text-align: center;">
  <img src="/images/Photo Identité.jpg?raw=true" alt="Profile Photo" style="width:200px; border-radius:100px;"/>
  </div>
  <div style="text-align: justify;">
    Aerospace Engineering student at ISAE-SUPAERO and UPC, driven by curiosity and motivated to contribute to innovation in the aerospace sector. I am particularly interested in research and development and propulsion technologies, and I look forward to expanding my skills and knowledge in this exciting field.
    The following portfolio features projects I've worked on or currently working on in aerospace engineering, as well as other fields.
  </div>
  <br><br>
  <a href="https://www.linkedin.com/in/gonzalocampos/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
include:
  - assets/css/style.css
google_analytics: UA-000000-0
